from __future__ import annotations

import json
import os
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    import anthropic as _anthropic

_client: Optional["LLMClient"] = None


class LLMClient:
    def __init__(self, client) -> None:
        self._client = client

    def generate_adr_body(
        self,
        title: str,
        rationale: str,
        alternatives_summary: str = "",
        constraints: list[str] | None = None,
        supersedes: list[str] | None = None,
    ) -> tuple[str, str, str]:
        """Return (context_text, decision_text, consequences_text) generated by LLM."""
        constraints_str = ", ".join(constraints or []) or "none"
        supersedes_str = ", ".join(supersedes or []) or "none"
        prompt = (
            f"You are writing an Architecture Decision Record (ADR).\n\n"
            f"Title: {title}\n"
            f"Rationale provided by the engineer: {rationale}\n"
            f"Alternatives considered: {alternatives_summary or 'none provided'}\n"
            f"Constraints depended on: {constraints_str}\n"
            f"Supersedes: {supersedes_str}\n\n"
            f"Generate three concise sections for this ADR:\n"
            f"1. Context: the background and problem that prompted this decision (2-4 sentences)\n"
            f"2. Decision: what was decided (1-3 sentences)\n"
            f"3. Consequences: what follows from this decision, positive and negative (2-4 sentences)\n\n"
            f'Respond with only a JSON object: {{"context": "...", "decision": "...", "consequences": "..."}}'
        )

        response = self._client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )
        text = response.content[0].text.strip()
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            # Best-effort: return raw text in context field
            return text, "", ""

        return (
            data.get("context", ""),
            data.get("decision", ""),
            data.get("consequences", ""),
        )

    def generate_promotion_body(
        self,
        title: str,
        context_provided: str,
        existing_context: str = "",
    ) -> tuple[str, str, str]:
        """Generate ADR body for promoting an observed entry."""
        prompt = (
            f"You are completing an Architecture Decision Record (ADR) for an existing dependency.\n\n"
            f"Title: {title}\n"
            f"Context provided: {context_provided}\n"
            f"Existing notes: {existing_context or 'none'}\n\n"
            f"Generate three concise sections:\n"
            f"1. Context: why this dependency exists and what problem it solves (2-4 sentences)\n"
            f"2. Decision: the choice that was made (1-3 sentences)\n"
            f"3. Consequences: what follows from this choice (2-4 sentences)\n\n"
            f'Respond with only a JSON object: {{"context": "...", "decision": "...", "consequences": "..."}}'
        )

        response = self._client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )
        text = response.content[0].text.strip()
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            return text, "", ""

        return (
            data.get("context", ""),
            data.get("decision", ""),
            data.get("consequences", ""),
        )


def get_client() -> LLMClient:
    global _client
    if _client is None:
        try:
            import anthropic
            _client = LLMClient(anthropic.Anthropic())
        except Exception as exc:
            raise RuntimeError(
                "Failed to initialize Anthropic client. "
                "Ensure ANTHROPIC_API_KEY is set."
            ) from exc
    return _client


def set_client(client: LLMClient) -> None:
    global _client
    _client = client
